version: "3"

services:
    pzserver:
        platform: linux/x86_64
        container_name: pzserver
        build:
            context: pzserver
        ports:
            - "16261:16261"
            - "16262:16262"
        env_file:
            - .env
        volumes:
            - ./volumes/pzserver/Zomboid/Server:/home/pzuser/Zomboid/Server/
            - ./volumes/pzserver/Zomboid/Saves:/home/pzuser/Zomboid/Saves/
            - ./volumes/pzserver/Zomboid/db:/home/pzuser/Zomboid/db/
            - ./volumes/pzserver/Zomboid/Logs:/home/pzuser/Zomboid/Logs/
            - ./volumes/pzserver/Zomboid/backups:/home/pzuser/Zomboid/backups/
            - ./volumes/pzserver/Zomboid/Mods:/opt/pzserver/steamapps/workshop/content
