version: "3.7"

services:
    pzserver:
        platform: linux/x86_64
        container_name: pzserver
        build:
            context: pzserver
        env_file:
            - .env
        volumes:
            - ./volumes/pzserver/Zomboid/Server:/home/pzuser/Zomboid/Server/
            - ./volumes/pzserver/Zomboid/Saves:/home/pzuser/Zomboid/Saves/
            - ./volumes/pzserver/Zomboid/db:/home/pzuser/Zomboid/db/
            - ./volumes/pzserver/Zomboid/Logs:/home/pzuser/Zomboid/Logs/
            - ./volumes/pzserver/Zomboid/backups:/home/pzuser/Zomboid/backups/
        network_mode: "host"
