version: "3.7"

services:
    pzserver:
        platform: linux/x86_64
        container_name: pzserver
        build:
            context: pzserver
        env_file:
            - .env
        volumes:
            - ./volumes/pzserver/Zomboid/Server:/root/Zomboid/Server/
            - ./volumes/pzserver/Zomboid/Saves:/root/Zomboid/Saves/
            - ./volumes/pzserver/Zomboid/db:/root/Zomboid/db/
            - ./volumes/pzserver/Zomboid/Logs:/root/Zomboid/Logs/
            - ./volumes/pzserver/Zomboid/backups:/root/Zomboid/backups/
        network_mode: "host"
